### ISSUE TITLE
Doesn't work at ubuntu 22

### ISSUE THREAD

**Issue by IrvanWijayaSardam** [vannszs/HotWalletBot#1]
i've already install all the requirement, and when i run the script, the log is just "Berhasil login"

![image](https://github.com/vannszs/HotWalletBot/assets/43365154/dc95bbe4-83e0-4426-b20f-f4ff77d9a2fc)

**Comment by vannszs** [comment]
Hi, are u using latest version from release?

**Comment by IrvanWijayaSardam** [comment]
yes i'm using the latest version

**Comment by vannszs** [comment]
I think thats not the latest version 
![IMG_20240216_105133](https://github.com/vannszs/HotWalletBot/assets/56658721/cc823c83-08a3-4946-b3fc-6065753c5713)

The latest version will print "main start on wallet 0" not "main start on seed 0"

**Comment by IrvanWijayaSardam** [comment]
I think it's already patched by the HotWallet developer

**Comment by vannszs** [comment]
I'll check it tonight and let u know the result, cheers

**Comment by vannszs** [comment]
new versin relese, pls check
